//! The Swift mirrors of the values the phone bridge carries, generated from
//! their Rust definitions: `cargo run -p xtask -- swift-types` writes them
//! and `--check` fails when the committed file differs, so a hand edit or a
//! Rust change without a regeneration cannot land.
//!
//! The Rust values serialize with serde's defaults, and their schemas come
//! from schemars. A struct becomes a Swift struct whose coding keys are the
//! Rust field names; a string-only enum becomes a raw-value enum; any other
//! enum is serde's externally tagged form, `"Unit"` or `{"Variant": ..}`,
//! with its Codable written out. Any schema shape outside those fails the
//! generation rather than producing a mirror that decodes wrongly.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use schemars::generate::SchemaSettings;
use serde_json::{Map, Value};

/// Where the mirrors live, from the repository root.
pub const OUTPUT: &str = "apps/apple/Packages/AmuxCore/Sources/AmuxValues/Values.swift";

/// Every value the bridge hands over or takes, by its root types; what
/// they hold comes along.
pub fn definitions() -> Map<String, Value> {
    let mut generator = SchemaSettings::draft2020_12().into_generator();
    macro_rules! roots {
        ($($ty:ty),* $(,)?) => { $( generator.subschema_for::<$ty>(); )* };
    }
    roots!(
        model::AgentKey,
        model::Attention,
        model::BlobStatus,
        model::Connection,
        model::Composer,
        model::PhaseView,
        model::Activity,
        model::InputState,
        ui_view::Row,
        ui_view::AskCard,
        ui_view::Pick,
        ui_view::Strip,
        ui_view::ComposerView,
        ui_view::QueuedRow,
        ui_view::OutboxRow,
        ui_view::FleetRow,
        ui_view::FleetCard,
        ui_view::FamilyHeader,
        ui_view::Away,
        ui_view::ReviewDoc,
        ui_view::Segment,
        app_runtime::values::StartConfig,
        app_runtime::values::ChatChanges,
        app_runtime::values::ChatFrame,
        app_runtime::values::RowOptions,
        app_runtime::values::Draft,
        app_runtime::values::FrozenReview,
        app_runtime::values::SendOutcome,
        app_runtime::values::ActOutcome,
        app_runtime::values::PageOutcome,
        app_runtime::values::HostView,
        app_runtime::values::FleetChanges,
        app_runtime::values::PairRequest,
        app_runtime::values::PendingPair,
        app_runtime::values::Roster,
        app_runtime::values::Found,
        app_runtime::values::AccountView,
        app_runtime::values::Bearer,
        app_runtime::values::NewAgent,
        app_runtime::values::Directories,
        app_runtime::values::AgentAct,
    );
    generator.take_definitions(true)
}

/// `swift-types [--check]`, run from anywhere in the repository.
pub fn main(args: &[String]) -> std::result::Result<(), Box<dyn std::error::Error>> {
    let check = match args {
        [] => false,
        [flag] if flag == "--check" => true,
        _ => return Err("usage: xtask swift-types [--check]".into()),
    };
    let path = repository().join(OUTPUT);
    let generated = generate(&definitions())?;
    if check {
        let committed = std::fs::read_to_string(&path).unwrap_or_default();
        if committed != generated {
            return Err(format!(
                "{} differs from the Rust definitions; run `cargo run -p xtask -- swift-types` \
                 and commit the result (the file is generated: never edit it by hand)",
                path.display()
            )
            .into());
        }
        println!("{} matches the Rust definitions", path.display());
    } else {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, generated)?;
        println!("wrote {}", path.display());
    }
    Ok(())
}

fn repository() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("xtask lives two levels under the repository")
        .to_owned()
}

type Result<T> = std::result::Result<T, String>;

/// The Swift source for every definition, sorted by name.
pub fn generate(definitions: &Map<String, Value>) -> Result<String> {
    let mut out = String::from(
        "// Generated by `cargo run -p xtask -- swift-types` from the Rust definitions of\n\
         // the values the phone bridge carries. Do not edit: change the Rust and\n\
         // regenerate; `--check` fails on any difference.\n\n\
         import Foundation\n",
    );
    let names: BTreeSet<&String> = definitions.keys().collect();
    for name in names {
        let schema = &definitions[name.as_str()];
        out.push('\n');
        out.push_str(&declaration(name, schema)?);
    }
    Ok(out)
}

fn declaration(name: &str, schema: &Value) -> Result<String> {
    let doc = docs(schema, "");
    if let Some(variants) = schema.get("oneOf").and_then(Value::as_array) {
        return Ok(doc + &tagged_enum(name, variants)?);
    }
    match schema.get("type").and_then(Value::as_str) {
        Some("object") => Ok(doc + &structure(name, schema)?),
        Some("string") => {
            let cases = schema
                .get("enum")
                .and_then(Value::as_array)
                .ok_or_else(|| format!("{name}: a string schema without cases"))?;
            let cases = cases
                .iter()
                .map(|case| {
                    case.as_str()
                        .map(|case| (case.to_owned(), None))
                        .ok_or_else(|| format!("{name}: a case that is not a string"))
                })
                .collect::<Result<Vec<_>>>()?;
            Ok(doc + &string_enum(name, &cases))
        }
        _ => Err(format!("{name}: an unsupported schema {schema}")),
    }
}

// --- structs ---------------------------------------------------------------

/// A property as Swift declares it.
struct Field {
    json: String,
    swift: String,
    ty: String,
    doc: String,
}

/// The object's properties: required ones in declaration order, then the
/// rest by name. An optional property is a Swift optional.
fn fields(owner: &str, schema: &Value) -> Result<Vec<Field>> {
    let empty = Map::new();
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .unwrap_or(&empty);
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|names| names.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let mut order: Vec<&str> = required.clone();
    order.extend(
        properties
            .keys()
            .map(String::as_str)
            .filter(|name| !required.contains(name)),
    );
    order
        .into_iter()
        .map(|json| {
            let property = properties
                .get(json)
                .ok_or_else(|| format!("{owner}: {json} is required but has no schema"))?;
            let (ty, nullable) = swift_type(owner, property)?;
            let optional = nullable || !required.contains(&json);
            Ok(Field {
                json: json.to_owned(),
                swift: identifier(&camel(json)),
                ty: if optional { format!("{ty}?") } else { ty },
                doc: docs(property, "    "),
            })
        })
        .collect()
}

fn structure(name: &str, schema: &Value) -> Result<String> {
    let fields = fields(name, schema)?;
    for field in &fields {
        if field.ty.trim_end_matches('?') == name {
            return Err(format!(
                "{name} holds itself directly; Swift structs cannot"
            ));
        }
    }
    let mut out = format!("public struct {name}: Codable, Hashable, Sendable {{\n");
    for field in &fields {
        let _ = writeln!(
            out,
            "{}    public var {}: {}",
            field.doc, field.swift, field.ty
        );
    }
    let params = fields
        .iter()
        .map(|field| format!("{}: {}", field.swift, field.ty))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!("\n    public init({params}) {{\n"));
    for field in &fields {
        let _ = writeln!(out, "        self.{0} = {0}", field.swift);
    }
    out.push_str("    }\n");
    if !fields.is_empty() {
        out.push('\n');
        out.push_str(&coding_keys("CodingKeys", &fields, "    "));
    }
    out.push_str("}\n");
    Ok(out)
}

fn coding_keys(name: &str, fields: &[Field], indent: &str) -> String {
    let mut out = format!("{indent}private enum {name}: String, CodingKey {{\n");
    for field in fields {
        if field.swift == field.json {
            let _ = writeln!(out, "{indent}    case {}", field.swift);
        } else {
            let _ = writeln!(out, "{indent}    case {} = \"{}\"", field.swift, field.json);
        }
    }
    out.push_str(&format!("{indent}}}\n"));
    out
}

// --- enums -----------------------------------------------------------------

fn string_enum(name: &str, cases: &[(String, Option<String>)]) -> String {
    let mut out =
        format!("public enum {name}: String, Codable, Hashable, Sendable, CaseIterable {{\n");
    for (case, doc) in cases {
        if let Some(doc) = doc {
            out.push_str(&doc_lines(doc, "    "));
        }
        let _ = writeln!(
            out,
            "    case {} = \"{case}\"",
            identifier(&lower_first(case))
        );
    }
    out.push_str("}\n");
    out
}

/// What a variant carries.
enum Payload {
    Unit,
    /// A newtype variant: one value of this Swift type.
    Value(String),
    /// A struct variant: named fields.
    Fields(Vec<Field>),
}

struct Variant {
    json: String,
    swift: String,
    doc: String,
    payload: Payload,
}

fn variants(name: &str, schemas: &[Value]) -> Result<Vec<Variant>> {
    let mut out = Vec::new();
    for schema in schemas {
        let doc = docs(schema, "    ");
        if let Some(case) = schema.get("const").and_then(Value::as_str) {
            out.push(unit(case, doc));
        } else if let Some(cases) = schema.get("enum").and_then(Value::as_array) {
            for case in cases {
                let case = case
                    .as_str()
                    .ok_or_else(|| format!("{name}: a case that is not a string"))?;
                out.push(unit(case, doc.clone()));
            }
        } else if schema.get("type").and_then(Value::as_str) == Some("object") {
            let properties = schema
                .get("properties")
                .and_then(Value::as_object)
                .filter(|properties| properties.len() == 1)
                .ok_or_else(|| format!("{name}: a variant that is not externally tagged"))?;
            let (json, payload) = properties.iter().next().expect("one property");
            let owner = format!("{name}.{json}");
            let payload = if payload.get("type").and_then(Value::as_str) == Some("object")
                && payload.get("properties").is_some()
            {
                Payload::Fields(fields(&owner, payload)?)
            } else {
                let (ty, nullable) = swift_type(&owner, payload)?;
                Payload::Value(if nullable { format!("{ty}?") } else { ty })
            };
            out.push(Variant {
                json: json.clone(),
                swift: identifier(&lower_first(json)),
                doc,
                payload,
            });
        } else {
            return Err(format!("{name}: an unsupported variant {schema}"));
        }
    }
    Ok(out)
}

fn unit(case: &str, doc: String) -> Variant {
    Variant {
        json: case.to_owned(),
        swift: identifier(&lower_first(case)),
        doc,
        payload: Payload::Unit,
    }
}

fn tagged_enum(name: &str, schemas: &[Value]) -> Result<String> {
    let variants = variants(name, schemas)?;
    if variants
        .iter()
        .all(|variant| matches!(variant.payload, Payload::Unit))
    {
        let cases: Vec<(String, Option<String>)> = variants
            .iter()
            .map(|variant| {
                let doc = (!variant.doc.is_empty()).then(|| undoc(&variant.doc));
                (variant.json.clone(), doc)
            })
            .collect();
        return Ok(string_enum(name, &cases));
    }
    let mut out = format!("public enum {name}: Codable, Hashable, Sendable {{\n");
    for variant in &variants {
        out.push_str(&variant.doc);
        match &variant.payload {
            Payload::Unit => {
                let _ = writeln!(out, "    case {}", variant.swift);
            }
            Payload::Value(ty) => {
                let _ = writeln!(out, "    case {}({ty})", variant.swift);
            }
            Payload::Fields(fields) => {
                let params = fields
                    .iter()
                    .map(|field| format!("{}: {}", field.swift, field.ty))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(out, "    case {}({params})", variant.swift);
            }
        }
    }

    let tagged: Vec<&Variant> = variants
        .iter()
        .filter(|variant| !matches!(variant.payload, Payload::Unit))
        .collect();
    let units: Vec<&Variant> = variants
        .iter()
        .filter(|variant| matches!(variant.payload, Payload::Unit))
        .collect();

    out.push_str("\n    private enum Tag: String, CodingKey {\n");
    for variant in &tagged {
        let _ = writeln!(out, "        case {} = \"{}\"", variant.swift, variant.json);
    }
    out.push_str("    }\n");
    for variant in &tagged {
        if let Payload::Fields(fields) = &variant.payload {
            out.push('\n');
            out.push_str(&coding_keys(&keys_name(variant), fields, "    "));
        }
    }

    // Decoding: a bare string names a unit variant; an object with one key
    // names any other.
    out.push_str("\n    public init(from decoder: any Decoder) throws {\n");
    if !units.is_empty() {
        out.push_str(
            "        if let _single = try? decoder.singleValueContainer(),\n           \
             let _name = try? _single.decode(String.self)\n        {\n            switch _name {\n",
        );
        for variant in &units {
            let _ = writeln!(
                out,
                "            case \"{}\": self = .{}",
                variant.json, variant.swift
            );
        }
        let _ = writeln!(
            out,
            "            default:\n                throw DecodingError.dataCorruptedError(\n                    \
             in: _single, debugDescription: \"no {name} is named \\(_name)\")\n            }}\n            \
             return\n        }}"
        );
    }
    out.push_str("        let _container = try decoder.container(keyedBy: Tag.self)\n");
    let _ = writeln!(
        out,
        "        guard _container.allKeys.count == 1, let _tag = _container.allKeys.first else {{\n            \
         throw DecodingError.dataCorrupted(\n                .init(\n                    \
         codingPath: decoder.codingPath,\n                    \
         debugDescription: \"a {name} names exactly one variant\"))\n        }}"
    );
    out.push_str("        switch _tag {\n");
    for variant in &tagged {
        let _ = writeln!(out, "        case .{}:", variant.swift);
        match &variant.payload {
            Payload::Unit => unreachable!("filtered"),
            Payload::Value(ty) => {
                let _ = writeln!(
                    out,
                    "            self = .{}(try _container.{}({}.self, forKey: .{}))",
                    variant.swift,
                    decode_call(ty),
                    ty.trim_end_matches('?'),
                    variant.swift
                );
            }
            Payload::Fields(fields) => {
                let _ = writeln!(
                    out,
                    "            let _fields = try _container.nestedContainer(\n                \
                     keyedBy: {}.self, forKey: .{})",
                    keys_name(variant),
                    variant.swift
                );
                let args = fields
                    .iter()
                    .map(|field| {
                        format!(
                            "\n                {}: try _fields.{}({}.self, forKey: .{})",
                            field.swift,
                            decode_call(&field.ty),
                            field.ty.trim_end_matches('?'),
                            field.swift
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(",");
                let _ = writeln!(out, "            self = .{}({args})", variant.swift);
            }
        }
    }
    out.push_str("        }\n    }\n");

    out.push_str(
        "\n    public func encode(to encoder: any Encoder) throws {\n        switch self {\n",
    );
    for variant in &variants {
        match &variant.payload {
            Payload::Unit => {
                let _ = writeln!(
                    out,
                    "        case .{}:\n            var _container = encoder.singleValueContainer()\n            \
                     try _container.encode(\"{}\")",
                    variant.swift, variant.json
                );
            }
            Payload::Value(ty) => {
                let _ = writeln!(
                    out,
                    "        case .{0}(let _value):\n            \
                     var _container = encoder.container(keyedBy: Tag.self)\n            \
                     try _container.{1}(_value, forKey: .{0})",
                    variant.swift,
                    encode_call(ty)
                );
            }
            Payload::Fields(fields) => {
                let bindings = fields
                    .iter()
                    .map(|field| format!("let {}", field.swift))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(
                    out,
                    "        case .{0}({bindings}):\n            \
                     var _container = encoder.container(keyedBy: Tag.self)\n            \
                     var _fields = _container.nestedContainer(keyedBy: {1}.self, forKey: .{0})",
                    variant.swift,
                    keys_name(variant)
                );
                for field in fields {
                    let _ = writeln!(
                        out,
                        "            try _fields.{}({1}, forKey: .{1})",
                        encode_call(&field.ty),
                        field.swift
                    );
                }
            }
        }
    }
    out.push_str("        }\n    }\n}\n");
    Ok(out)
}

fn keys_name(variant: &Variant) -> String {
    format!("{}Keys", upper_first(&variant.swift.replace('`', "")))
}

fn decode_call(ty: &str) -> &'static str {
    if ty.ends_with('?') {
        "decodeIfPresent"
    } else {
        "decode"
    }
}

fn encode_call(ty: &str) -> &'static str {
    if ty.ends_with('?') {
        "encodeIfPresent"
    } else {
        "encode"
    }
}

// --- types -----------------------------------------------------------------

/// The Swift type for a property's schema, and whether it may be null.
fn swift_type(owner: &str, schema: &Value) -> Result<(String, bool)> {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return Ok((referenced(owner, reference)?, false));
    }
    if let Some(any) = schema.get("anyOf").and_then(Value::as_array) {
        let (nulls, others): (Vec<&Value>, Vec<&Value>) = any
            .iter()
            .partition(|schema| schema.get("type").and_then(Value::as_str) == Some("null"));
        return match (nulls.len(), others.as_slice()) {
            (1, [only]) => Ok((swift_type(owner, only)?.0, true)),
            _ => Err(format!("{owner}: an unsupported union {schema}")),
        };
    }
    let (ty, nullable) = match schema.get("type") {
        Some(Value::String(ty)) => (ty.as_str(), false),
        Some(Value::Array(types)) => {
            let named: Vec<&str> = types.iter().filter_map(Value::as_str).collect();
            match named.as_slice() {
                [ty, "null"] | ["null", ty] => (*ty, true),
                _ => return Err(format!("{owner}: an unsupported type list {schema}")),
            }
        }
        _ => return Err(format!("{owner}: a property with no type {schema}")),
    };
    let swift = match ty {
        "string" => "String".to_owned(),
        "boolean" => "Bool".to_owned(),
        "number" => "Double".to_owned(),
        "integer" => integer(owner, schema)?.to_owned(),
        "array" => {
            if schema.get("prefixItems").is_some() {
                return Err(format!(
                    "{owner}: a tuple; give it a struct with named fields"
                ));
            }
            let items = schema
                .get("items")
                .ok_or_else(|| format!("{owner}: an array without items"))?;
            let (item, nullable) = swift_type(owner, items)?;
            format!("[{item}{}]", if nullable { "?" } else { "" })
        }
        other => return Err(format!("{owner}: an unsupported type {other}")),
    };
    Ok((swift, nullable))
}

fn integer(owner: &str, schema: &Value) -> Result<&'static str> {
    Ok(match schema.get("format").and_then(Value::as_str) {
        Some("uint8") => "UInt8",
        Some("uint16") => "UInt16",
        Some("uint32") => "UInt32",
        Some("uint64") => "UInt64",
        Some("uint") => "UInt",
        Some("int8") => "Int8",
        Some("int16") => "Int16",
        Some("int32") => "Int32",
        Some("int64") => "Int64",
        Some("int") => "Int",
        other => return Err(format!("{owner}: an integer of format {other:?}")),
    })
}

fn referenced(owner: &str, reference: &str) -> Result<String> {
    reference
        .strip_prefix("#/$defs/")
        .map(ToOwned::to_owned)
        .ok_or_else(|| format!("{owner}: an unsupported reference {reference}"))
}

// --- names and docs --------------------------------------------------------

fn camel(snake: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for c in snake.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn lower_first(name: &str) -> String {
    let mut chars = name.chars();
    chars
        .next()
        .map(|first| first.to_lowercase().chain(chars).collect())
        .unwrap_or_default()
}

fn upper_first(name: &str) -> String {
    let mut chars = name.chars();
    chars
        .next()
        .map(|first| first.to_uppercase().chain(chars).collect())
        .unwrap_or_default()
}

/// Swift's reserved words, escaped where a name is one.
fn identifier(name: &str) -> String {
    const RESERVED: &[&str] = &[
        "associatedtype",
        "break",
        "case",
        "catch",
        "class",
        "continue",
        "default",
        "defer",
        "deinit",
        "do",
        "else",
        "enum",
        "extension",
        "fallthrough",
        "false",
        "fileprivate",
        "for",
        "func",
        "guard",
        "if",
        "import",
        "in",
        "init",
        "inout",
        "internal",
        "is",
        "let",
        "nil",
        "operator",
        "private",
        "protocol",
        "public",
        "repeat",
        "rethrows",
        "return",
        "self",
        "static",
        "struct",
        "subscript",
        "super",
        "switch",
        "throw",
        "throws",
        "true",
        "try",
        "typealias",
        "var",
        "where",
        "while",
        "Self",
    ];
    if RESERVED.contains(&name) {
        format!("`{name}`")
    } else {
        name.to_owned()
    }
}

fn docs(schema: &Value, indent: &str) -> String {
    schema
        .get("description")
        .and_then(Value::as_str)
        .map(|text| doc_lines(text, indent))
        .unwrap_or_default()
}

fn doc_lines(text: &str, indent: &str) -> String {
    text.lines()
        .map(|line| {
            if line.is_empty() {
                format!("{indent}///\n")
            } else {
                format!("{indent}/// {line}\n")
            }
        })
        .collect()
}

/// The text of doc lines made by [`doc_lines`].
fn undoc(doc: &str) -> String {
    doc.lines()
        .map(|line| {
            line.trim_start()
                .trim_start_matches("///")
                .trim_start_matches(' ')
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn the_committed_mirrors_match_the_rust_definitions() {
        let committed = std::fs::read_to_string(repository().join(OUTPUT)).unwrap_or_default();
        assert!(
            committed == generate(&definitions()).unwrap(),
            "run `cargo run -p xtask -- swift-types` and commit the result"
        );
    }

    /// Every public value type in the crates the bridge reads from has a
    /// mirror, except the ones that never cross it.
    #[test]
    fn every_public_view_value_has_a_swift_mirror() {
        const STAY_IN_RUST: &[&str] = &[
            // The answer body a choice sends: the phone names the choice.
            "Answer",
            // Borrowed option types; RowOptions carries them across.
            "ToolRows",
            "ChatOptions",
        ];
        let definitions = definitions();
        let root = repository();
        let mut missing = Vec::new();
        for dir in [
            "crates/model/src",
            "crates/ui-view/src",
            "crates/app-runtime/src/values.rs",
        ] {
            let path = root.join(dir);
            let files = if path.is_dir() {
                std::fs::read_dir(&path)
                    .unwrap()
                    .map(|entry| entry.unwrap().path())
                    .collect()
            } else {
                vec![path]
            };
            for file in files {
                let text = std::fs::read_to_string(&file).unwrap();
                for line in text.lines() {
                    let line = line.trim_start();
                    let Some(rest) = line
                        .strip_prefix("pub struct ")
                        .or_else(|| line.strip_prefix("pub enum "))
                    else {
                        continue;
                    };
                    let name: String = rest
                        .chars()
                        .take_while(|c| c.is_alphanumeric() || *c == '_')
                        .collect();
                    if !STAY_IN_RUST.contains(&name.as_str()) && !definitions.contains_key(&name) {
                        missing.push(format!("{name} ({})", file.display()));
                    }
                }
            }
        }
        assert!(missing.is_empty(), "no Swift mirror for: {missing:#?}");
    }

    #[test]
    fn a_shape_swift_cannot_mirror_fails_the_generation() {
        let tuple = json!({"T": {"type": "object", "properties": {
            "pair": {"type": "array", "prefixItems": [{"type": "string"}, {"type": "number"}]}
        }, "required": ["pair"]}});
        let error = generate(tuple.as_object().unwrap()).unwrap_err();
        assert!(error.contains("tuple"), "{error}");
        let untagged = json!({"U": {"oneOf": [{"type": "object", "properties": {
            "a": {"type": "string"}, "b": {"type": "string"}
        }}]}});
        assert!(generate(untagged.as_object().unwrap()).is_err());
    }

    #[test]
    fn names_follow_swift_and_keep_the_rust_keys() {
        let schema = json!({"S": {"type": "object", "properties": {
            "max_attempts": {"type": "integer", "format": "uint32"},
            "default": {"type": ["string", "null"]}
        }, "required": ["max_attempts"]}});
        let swift = generate(schema.as_object().unwrap()).unwrap();
        assert!(swift.contains("public var maxAttempts: UInt32"), "{swift}");
        assert!(
            swift.contains("case maxAttempts = \"max_attempts\""),
            "{swift}"
        );
        assert!(swift.contains("public var `default`: String?"), "{swift}");
    }
}
