/* automatically generated by rust-bindgen 0.71.1 */

pub(super) const kIOReturnSuccess: u32 = 0;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub(super) struct __CFString {
    _unused: [u8; 0],
}
pub(super) type CFStringRef = *const __CFString;
pub(super) type kern_return_t = ::std::os::raw::c_int;
pub(super) type IOReturn = kern_return_t;
pub(super) type IOPMAssertionID = u32;
pub(super) type IOPMAssertionLevel = u32;
pub(super) const kIOPMAssertionLevelOff: _bindgen_ty_36 = 0;
pub(super) const kIOPMAssertionLevelOn: _bindgen_ty_36 = 255;
pub(super) type _bindgen_ty_36 = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub(super) fn IOPMAssertionRelease(AssertionID: IOPMAssertionID) -> IOReturn;
}
unsafe extern "C" {
    pub(super) fn IOPMAssertionCreateWithName(
        AssertionType: CFStringRef,
        AssertionLevel: IOPMAssertionLevel,
        AssertionName: CFStringRef,
        AssertionID: *mut IOPMAssertionID,
    ) -> IOReturn;
}
