//! The reified input vocabulary: every stimulus the reducer can observe.
//!
//! Every variant is serde-serializable so a recorded Msg log replays into an
//! identical Model (`docs/UI.md`, "The reducer core"). IDs and observed time
//! enter through Msgs — the reducer itself never reads a clock or mints an id.
//!
//! This module is part of the pure reducer core: no IO, no clocks, no
//! randomness may be imported here.

use std::path::PathBuf;

use amux::{Agent, AgentId, HostEntry, HostId};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Identity of one dispatched operation. Minted by the shell (or the test
/// harness) and carried through `Msg::Command` → `Effect::Rpc` →
/// `Msg::OpResult`; async results are matched back by this id and results for
/// unknown (superseded) ops are discarded.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct OpId(pub Uuid);

/// Backpressure class of a Msg kind (`docs/UI.md`, "Flow"). The Ephemeral
/// membership rule classifies for correctness; this classifies for flow:
/// lossless producers wait on a bounded queue, coalescable kinds are batched
/// into one Msg before the recorder sees them, droppable is Ephemeral only.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FlowClass {
    Lossless,
    Coalescable,
    Droppable,
}

/// The single ordered input stream folded by `update`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "msg", rename_all = "snake_case")]
pub enum Msg {
    /// A client write. The only write surface; dispatch returns the `OpId`
    /// and the outcome comes back as state (a finished op), never as a
    /// callback.
    Command { op: OpId, command: Command },
    /// Server-pushed connection and inventory events, mapped from
    /// `amux::Client` subscription streams by the shell.
    Server(ServerMsg),
    /// Result of an `Effect::Rpc`. Resolves pending-operation state only —
    /// never entity state (subscriptions are the sole entity authority).
    OpResult { op: OpId, outcome: OpOutcome },
    /// Per-agent session-stream events. High-rate entries arrive coalesced:
    /// the recorded Msg is the batch.
    Stream { agent: AgentId, event: StreamMsg },
    /// The user attached to an agent — a reified interaction fact. The
    /// subscription policy widens to any agent the user interacts with, so
    /// its attention stays fresh after detach.
    UserAttached { agent: AgentId },
    /// Observed time for time-dependent display. Data, not a timer: the shell
    /// schedules ticks only while something on screen needs them.
    Tick { now: DateTime<Utc> },
}

impl Msg {
    /// Every Msg kind answers its flow class (`docs/UI.md`, "Flow").
    pub fn flow_class(&self) -> FlowClass {
        match self {
            Msg::Command { .. }
            | Msg::Server(_)
            | Msg::OpResult { .. }
            | Msg::UserAttached { .. } => FlowClass::Lossless,
            Msg::Stream { event, .. } => match event {
                StreamMsg::Batch { .. } => FlowClass::Coalescable,
                StreamMsg::Opened { .. } | StreamMsg::ReplayComplete | StreamMsg::Closed { .. } => {
                    FlowClass::Lossless
                }
            },
            Msg::Tick { .. } => FlowClass::Coalescable,
        }
    }
}

/// Client writes. Attach/detach is not a Command: raw attach is a terminal
/// handoff owned by the renderer shell, not reducer state.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "command", rename_all = "snake_case")]
pub enum Command {
    CreateAgent {
        /// Target host; `None` means the local daemon picks (its own host).
        host: Option<HostId>,
        /// Generated by the dispatching client — no form in V1.
        name: String,
        agent_type: amux::AgentType,
        working_dir: PathBuf,
    },
    RenameAgent {
        agent: AgentId,
        name: String,
    },
    DeleteAgent {
        agent: AgentId,
    },
    /// Submit a prompt to a Claude chat (B1/D2). Gated on phase by the
    /// reducer (`Model::claude_send_gate`); success renders the optimistic
    /// echo until the transcript row reconciles it.
    SendPrompt {
        agent: AgentId,
        text: String,
    },
    /// Answer the addressed ask (C5): the reducer encodes the typed answer
    /// through the C6 module and flips the ask to answered-optimistic.
    /// Only the HEAD of the queue may be answered — claude's remote menu
    /// displays nothing else, so a non-head target refuses without bytes.
    AnswerAsk {
        agent: AgentId,
        ask: u64,
        answer: crate::claude::encoding::AskAnswer,
    },
    /// Interrupt the session (D3): allowed in every state; the transcript
    /// records the interruption entry (B8).
    Interrupt {
        agent: AgentId,
    },
    /// Cycle the permission mode (D4, Shift+Tab). The mode fact returns
    /// via hook payloads — the cycle itself emits no transcript row.
    CyclePermissionMode {
        agent: AgentId,
    },
}

/// Connection and inventory events. Entity events are idempotent upserts —
/// "the state IS this", never "this happened".
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "server", rename_all = "snake_case")]
pub enum ServerMsg {
    /// A (re)connection to the daemon came up. The reducer opens a new epoch;
    /// the snapshot that follows replaces inventory once both `Synchronized`
    /// markers arrive.
    Connected {
        /// The daemon's own host id, read from the local device identity by
        /// the shell (the wire does not mark the local host).
        local_host_id: Option<HostId>,
    },
    Disconnected {
        reason: DisconnectReason,
    },
    HostUpserted {
        host: HostEntry,
    },
    HostRemoved {
        id: HostId,
    },
    /// Host snapshot complete for the current epoch.
    HostsSynchronized,
    AgentUpserted {
        agent: Agent,
    },
    AgentRemoved {
        id: AgentId,
    },
    /// Agent snapshot complete for the current epoch.
    AgentsSynchronized,
}

/// Why the daemon connection went away.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "reason", rename_all = "snake_case")]
pub enum DisconnectReason {
    ServerShutdown {
        detail: String,
    },
    TransportError {
        message: String,
    },
    /// Mapped from `ProtocolError::InvalidCredentials` /
    /// `AuthError::Unauthenticated`.
    AuthenticationRequired,
    ApplicationShutdown,
}

/// Result of an RPC effect. Entity payloads riding on a success are used to
/// resolve the op only — a stale rename response must never overwrite a newer
/// subscription upsert.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "outcome", rename_all = "snake_case")]
pub enum OpOutcome {
    AgentCreated {
        agent: Agent,
    },
    AgentRenamed {
        agent: Agent,
    },
    AgentDeleted,
    /// The keystroke program was injected under the seq guard. Injection
    /// is not confirmation: prompts confirm by echo reconciliation, ask
    /// answers by the transcript's resolution fact (C5).
    InputSent,
    Error {
        error: OpError,
    },
}

impl OpOutcome {
    pub fn is_error(&self) -> bool {
        matches!(self, OpOutcome::Error { .. })
    }
}

/// A failed operation, as shown in the status line.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct OpError {
    pub message: String,
    /// True when the failure was an authentication failure
    /// (`ProtocolError::InvalidCredentials`): the fleet degrades to the
    /// cloud-auth banner instead of a dead screen.
    pub auth_required: bool,
}

/// Per-agent session-stream lifecycle and content.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum StreamMsg {
    Opened {
        /// True when replay starts past the beginning of the stream (first
        /// replayed seq > 1): the fold over the tail must degrade to
        /// `Unknown` rather than guess (`docs/UI.md`, honest summaries).
        truncated: bool,
    },
    /// Coalesced structured entries. `at` is the shell's observed arrival
    /// time (time enters via Msgs), used for last-activity recency.
    Batch {
        at: DateTime<Utc>,
        entries: Vec<StreamEntry>,
    },
    ReplayComplete,
    Closed {
        reason: StreamCloseReason,
    },
}

/// One structured entry: an opaque JSON row plus its stream sequence number.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamEntry {
    pub seq: u64,
    pub payload: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "reason", rename_all = "snake_case")]
pub enum StreamCloseReason {
    AgentDeleted,
    AgentExited {
        exit_code: Option<i32>,
    },
    HostUnreachable,
    InternalError {
        detail: String,
    },
    TransportError {
        message: String,
    },
    AuthenticationRequired,
    /// Closed by the shell executing `Effect::CloseStream`.
    ClientClosed,
}

/// Reserved one-shot channel; uninhabited until the first genuine one-shot
/// exists.
///
/// Membership rule (`docs/UI.md`): something is ephemeral only if a client
/// that misses it entirely still renders a correct screen (a bell, a haptic,
/// a row flash). Unsequenced, droppable, never read by `update`. Anything
/// whose loss could make a screen wrong is state and goes through the Model.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Ephemeral {}
