[package]
name = "tui-fixtures"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
chrono = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
serde_json = { workspace = true }
tui = { workspace = true }
ui-runtime = { workspace = true }
ui-state = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
gethostname = { workspace = true }
tempfile = { workspace = true }
vt100 = "0.15"
