//! Conservative conversion of retained provider rows, never of folded UI state.

use std::path::Path;

use amux::testnet::script::{Reaction, Script, Step, Trigger};
use amux_ui::{Model, Msg, RecorderSnapshot, ServerMsg, StreamMsg, StructuredProtocol};
use anyhow::{Context, Result, ensure};
use serde::Deserialize;

#[derive(Debug, PartialEq, Eq, thiserror::Error)]
pub enum ConversionRefusal {
    #[error("EvictedHistory: checkpoint contains {rows} folded feed entries")]
    EvictedHistory { rows: u64 },
    #[error("PartialSession: require one uninterrupted stream starting at sequence 1")]
    PartialSession,
    #[error("UnsupportedLayer: {0}")]
    UnsupportedLayer(String),
    #[error("UnsupportedRow: {0} requires provider semantics absent from transcript playback")]
    UnsupportedRow(String),
    #[error("InvalidMessage at retained line {line}: {message}")]
    InvalidMessage { line: usize, message: String },
}

pub fn read_snapshot(path: &Path) -> Result<RecorderSnapshot> {
    #[derive(Deserialize)]
    struct Header {
        format_version: u32,
        checkpoint: Model,
    }
    let contents = std::fs::read_to_string(path).with_context(|| path.display().to_string())?;
    let mut lines = contents.lines();
    let header: Header = serde_json::from_str(lines.next().context("empty recorder snapshot")?)?;
    ensure!(
        header.format_version == amux_ui::MSGS_SCHEMA_VERSION,
        "unsupported recorder format {}",
        header.format_version
    );
    Ok(RecorderSnapshot {
        checkpoint: header.checkpoint,
        msgs: lines
            .filter(|line| !line.trim().is_empty())
            .map(str::to_owned)
            .collect(),
    })
}

/// Preserve raw transcript rows in a single reaction. The caller supplies the
/// playback trigger; interactive asks require an authored script with hooks.
pub fn script_from_report(snapshot: &RecorderSnapshot) -> Result<Script, ConversionRefusal> {
    let rows = snapshot
        .checkpoint
        .agents()
        .filter_map(|card| card.claude())
        .map(|layer| layer.evicted_entries() + layer.entry_count() as u64)
        .sum();
    if rows > 0 {
        return Err(ConversionRefusal::EvictedHistory { rows });
    }
    if snapshot
        .checkpoint
        .agents()
        .any(|card| snapshot.checkpoint.stream(card.agent.id).is_some())
    {
        return Err(ConversionRefusal::PartialSession);
    }
    let mut model = snapshot.checkpoint.clone();
    let mut session = None;
    let mut next_seq = 1;
    let mut closed = false;
    let mut jsonl = Vec::new();
    for (index, line) in snapshot.msgs.iter().enumerate() {
        let msg: Msg =
            serde_json::from_str(line).map_err(|error| ConversionRefusal::InvalidMessage {
                line: index + 1,
                message: error.to_string(),
            })?;
        match &msg {
            Msg::Server(ServerMsg::AgentUpserted { agent }) if session == Some(agent.id) => {
                if !matches!(
                    agent.kind,
                    amux::AgentKind::Claude {
                        driver: amux::ClaudeDriver::Pty,
                        ..
                    }
                ) {
                    return Err(ConversionRefusal::UnsupportedLayer(format!(
                        "{:?}",
                        agent.kind
                    )));
                }
            }
            Msg::Stream { agent, event } => {
                let card = model
                    .agent(*agent)
                    .ok_or(ConversionRefusal::PartialSession)?;
                if card.structured_protocol() != Some(StructuredProtocol::Claude) {
                    return Err(ConversionRefusal::UnsupportedLayer(format!(
                        "{:?}",
                        card.agent.kind
                    )));
                }
                match event {
                    StreamMsg::Opened { truncated } => {
                        if *truncated || session.is_some() {
                            return Err(ConversionRefusal::PartialSession);
                        }
                        session = Some(*agent);
                    }
                    StreamMsg::Batch { entries, .. } => {
                        if session != Some(*agent) || closed {
                            return Err(ConversionRefusal::PartialSession);
                        }
                        for entry in entries {
                            if entry.seq != next_seq {
                                return Err(ConversionRefusal::PartialSession);
                            }
                            next_seq += 1;
                            let kind = entry.payload["type"].as_str().unwrap_or("");
                            // Session transport markers are regenerated by the live
                            // provider. Semantic hook/ask rows cannot be inverted.
                            match kind {
                                "amux.transcript_ready" | "amux.claude.keymap" => {}
                                kind if kind.starts_with("amux.") => {
                                    return Err(ConversionRefusal::UnsupportedRow(kind.into()));
                                }
                                _ => jsonl.push(entry.payload.clone()),
                            }
                        }
                    }
                    StreamMsg::Closed { .. } | StreamMsg::ReplayComplete => {
                        if session != Some(*agent) || closed {
                            return Err(ConversionRefusal::PartialSession);
                        }
                        closed = matches!(event, StreamMsg::Closed { .. });
                    }
                }
            }
            _ => {}
        }
        // Only inventory is needed for protocol selection. Never fold rows into
        // a bounded UI feed and then mistake that projection for source history.
        if matches!(msg, Msg::Server(_)) {
            amux_ui::update(&mut model, msg);
        }
    }
    if jsonl.is_empty() {
        return Err(ConversionRefusal::PartialSession);
    }
    Ok(Script {
        reactions: vec![Reaction {
            on: Trigger::Any,
            play: vec![Step::Rows { jsonl }],
        }],
        ..Script::default()
    })
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use amux::testnet::script;
    use serde_json::json;

    use super::*;

    fn fixture(name: &str) -> RecorderSnapshot {
        read_snapshot(
            &Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("tests/fixtures/reports")
                .join(name)
                .join("msgs.jsonl"),
        )
        .unwrap()
    }

    #[tokio::test]
    async fn script_from_report_complete_rows_reach_the_provider_session() {
        let snapshot = fixture("complete");
        let script = script_from_report(&snapshot).unwrap();
        let Step::Rows { jsonl: expected } = &script.reactions[0].play[0] else {
            panic!("raw rows")
        };
        assert_eq!(expected.len(), 3);
        let (mut session, provider) = script::session(script.clone()).await.unwrap();
        let collect = tokio::spawn(async move {
            let mut rows = Vec::new();
            while rows.len() < 3 {
                if let claude::pty::PtyEvent::Transcript { row, .. } =
                    session.events.recv().await.unwrap()
                {
                    rows.push(row.as_value().clone());
                }
            }
            rows
        });
        provider
            .play(script.reactions[0].play.clone())
            .await
            .unwrap();
        let actual = tokio::time::timeout(Duration::from_secs(5), collect)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(&actual, expected);
        println!(
            "Converted script: {}",
            serde_json::to_string_pretty(&script).unwrap()
        );
        println!(
            "Provider transcript: {}",
            serde_json::to_string(&actual).unwrap()
        );
    }

    #[test]
    fn script_from_report_refuses_evicted_history_and_partial_session() {
        assert!(matches!(
            script_from_report(&fixture("truncated")),
            Err(ConversionRefusal::EvictedHistory { rows: 1 })
        ));
        assert_eq!(
            script_from_report(&fixture("mid_session")),
            Err(ConversionRefusal::PartialSession)
        );
        println!("truncated: EvictedHistory; mid_session: PartialSession");
    }

    #[test]
    fn script_from_report_rejects_gaps_reopens_mixed_layers_and_semantic_rows() {
        let snapshot = fixture("complete");
        let batch = snapshot
            .msgs
            .iter()
            .position(|s| s.contains("\"batch\""))
            .unwrap();
        for change in [
            "gap",
            "second_agent",
            "semantic",
            "malformed",
            "reopen",
            "codex",
        ] {
            let mut changed = snapshot.clone();
            let mut value: serde_json::Value = serde_json::from_str(&changed.msgs[batch]).unwrap();
            match change {
                "gap" => value["event"]["entries"][1]["seq"] = json!(9),
                "second_agent" => value["agent"] = json!("00000000-0000-0000-0000-000000000099"),
                "semantic" => {
                    value["event"]["entries"][0]["payload"]["type"] = json!("amux.claude.ask")
                }
                "malformed" => value["event"]["entries"][0]["seq"] = json!("invalid"),
                "reopen" => changed.msgs.push(changed.msgs[3].clone()),
                "codex" => {
                    let mut upsert: serde_json::Value =
                        serde_json::from_str(&changed.msgs[2]).unwrap();
                    upsert["agent"]["kind"] = json!({"kind":"codex"});
                    changed.msgs[2] = upsert.to_string();
                }
                _ => unreachable!(),
            }
            changed.msgs[batch] = value.to_string();
            assert!(script_from_report(&changed).is_err(), "{change}");
        }
    }
}
